management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    enable:
      all: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        database.read.operations: true
        database.write.operations: true
